#!/bin/bash
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_genomicscore.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_instruments_iscan.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_instruments_sequencing.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_instruments_novaseq.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_instruments_iseq.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_instruments_minion.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_instruments_geomx.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_collab_genomicscore.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_instruments_aviti.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/rsync_instruments_miseq.sh
/varidata/research/admin/tools/genomicsCoreFileMgmt/notifyFileAge.pl
/varidata/research/admin/tools/genomicsCoreFileMgmt/moveFilesToAWSStaging.pl
